version: '3.4'

services:
  agendatenis.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80"
      - "4000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "MinhaSenha!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  mongo:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
    ports:
    - "27017:27017"

  rabbitmq3:
    container_name: "agendatenis_rabbitmq"
    image: rabbitmq:3-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    # Porta AMPQ
    - '5672:5672'
    # Porta Painel Rabbit
    - '15672:15672'

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'