version: '3.4'

services:
  agendatenis.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Identity=Server=sqlserver,1433;Database=identity_db;User Id=sa;Password=MinhaSenha!;
      - ConnectionStrings__Jogadores=Server=sqlserver,1433;Database=jogadores_db;User Id=sa;Password=MinhaSenha!;
      - ConnectionStrings__Partidas=mongodb://root:MongoDB2023!@mongo:27017
      - ConnectionStrings__Redis=cache:6379
      - RabbitMQ__Host=rabbitmq3
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__CliendProvidedName=AgendaTenis
    ports:
      - "8000:80"
      - "4000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
      - mongo
      - rabbitmq3
      - cache

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "MinhaSenha!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  mongo:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
    ports:
    - "27017:27017"

  rabbitmq3:
    container_name: "agendatenis_rabbitmq"
    image: rabbitmq:3-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    - '5672:5672' # Porta AMPQ
    - '15672:15672' # Porta Painel Rabbit

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'